### PR TITLE
Refactoring + additional features (autoplay)

### PR DESCRIPTION
**Pull request by RogueM**

### CODE REVIEW

**Comment by RogueM** [comment]
there are a large number of changes, but here's a short list of the most important:
- Normal mode, distribution as per physical game
- Twigs and Leafs can be 'auto-played' by double click
- all modes include 76 cards (easy and master dropped some cards)
- card distribution can be seen on the left
- doom timer move to the right, besides the lamp
- doom timer is 10 seconds rather than 5 (can be changed with one variable)
- dead ends renamed to traps (for cosmetic reasons)
- some refactoring, to improve clarity and minimise redundancy
- simple server to host the program locally
- jQuery v1.12.4 included (optional, should work with previous)

... I think that' about all I can remember. Hopefully not too many bugs bugs (and in an ideal world none) have cropped in!

**Comment by davoid-avoid** [comment]
This is incredible! Thanks so much! I'll do some quick runs and upload. Fantastic work!

I'll try to refactor further in the future, I shamefully haven't really come back to this project in a long time.

**Comment by RogueM** [comment]
np, that was a good learning experience for me. There are a few rough edges, such as auto-play not available in the tutorial to minimise complexity, but that could be done at a later stage if deemed necessary.

**Comment by davoid-avoid** [comment]
Uploading. Thanks again! It's really great! 

I did change the hardwin count back to 0, but if it's preferable to have it open from the start, I can add the unlocked features to the menu html and remove the unlock code.

**Comment by RogueM** [comment]
oops, no, that was a leftover of my test!

**Comment by davoid-avoid** [comment]
Love the deck distribution HUD.

I might update that in the future to reflect the number of specific cards left in the draw deck, but am wondering if that would make it too easy/make it too apparent if you've lost?

**Comment by RogueM** [comment]
I thought about doing it, could be an option, though I probably wouldn't use it myself... which does not mean others wouldn't.

One thing I forgot to include is a TODO, I think it would be good to have so if anyone has spare time they could tackle the list. I know some people wanted the 'chuck a scored god to cancel a ghost' option... was planning to look at it at some point.

**Comment by davoid-avoid** [comment]
Yea. I could start tackling that. I don't see how it would be difficult. I can't this weekend, unfortunately, but it would just involve setting the laterns to be selectable, and then slapping that god back into the deck from the scored pile.

Man, this was my first coding project, and now, like, a year or two down the road, I can barely look at the code without just wanting to rewrite it all from the ground up, ha ha ha. What a messy pile of functions.

**Comment by davoid-avoid** [comment]
I also have to fix the modal, ha ha, I put it together it working on a laptop monitor and wow, it's kinda... all over the place.

I also might want to disable the deck view for the tutorial.. or play with the tutorial deck, because it's obvious the tut deck is just designed to pad out a ton of cards to control what the player gets and when.

**Comment by RogueM** [comment]
yes, that sort of was why I just disabled auto-play in the tutorial. Never coded with javascript before so if any improvement came with it, it's most accidental.

I was a bit hesitant to mess about too much with the code but as soon as I started with the double click it came apparent I needed to reshuffle a few things to not make an utter mess of it.

having my first 'live' game on your site on the laptop, I'll try on smaller screens later, could definitely be problematic.

**Comment by davoid-avoid** [comment]
Yea, one of my TODO's was to write media query powered CSS to adjust to various screen sizes, as a lot of people asked me for a more mobile friendly version.

**Comment by RogueM** [comment]
actually it's surprisingly serviceable on an iPad mini... that was a fluke, as I had no real possibility to test before (not that the minimal additional footprint of the optional distribution was too much of a concern). obviously a phone is a different matter - a mobile friendly version would be great in the future, time permitting!

**Comment by davoid-avoid** [comment]
I have been working with XCode a lot more at work, so maybe I'll create an app version someday.

I'm also torn on whether I should pretty it up one day or not, ha ha (create card flipping animations, etc).

**Comment by davoid-avoid** [comment]
Just turned off the distribution display for tutorial, just because it kinda lifts up the curtain a bit too much, ha ha ha.

**Comment by RogueM** [comment]
oh, yeah... that's the last thing I was working on, never occurred to me it was best disabled.

**Comment by davoid-avoid** [comment]
No problem! Really great work. I'd love to sit down and rethink the whole code structure of this game someday, but I'm glad it was fun to mess around with!

**Pull request merged**
